default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: 5
  timeout: 5000
  host: <%= ENV["DB_HOST"] %>

development:
  <<: *default
  database: <%= ENV["DATABASE"] %>

test:
  <<: *default
  database: <%= ENV["TEST_DATABASE"] %>

production:
  <<: *default
  database: <%= ENV["DATABASE"] %>
